FROM python:3.9

WORKDIR /app

COPY api.py /app
COPY my_model.keras /app
COPY requirements.txt /app

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Lancer FastAPI
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
